# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemap < Formula
  desc "Generate a brain map of your codebase for LLM context"
  homepage "https://github.com/JordanCoin/codemap"
  version "4.1.9"
  license "MIT"

  depends_on "ast-grep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordanCoin/codemap/releases/download/v4.1.9/codemap_4.1.9_darwin_amd64.tar.gz"
      sha256 "b65c66cf3f1b56473cfc31e5699565f4ba641d877b615a6496d06a71121fea5d"

      define_method(:install) do
        bin.install "codemap"
        (pkgshare/"sg-rules").install Dir["sg-rules/*.yml"] if Dir.exist?("sg-rules")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordanCoin/codemap/releases/download/v4.1.9/codemap_4.1.9_darwin_arm64.tar.gz"
      sha256 "436796bcb13624b7023d505b5ca1d0607548d9bb1f13fd35024e9e3f22255643"

      define_method(:install) do
        bin.install "codemap"
        (pkgshare/"sg-rules").install Dir["sg-rules/*.yml"] if Dir.exist?("sg-rules")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/codemap/releases/download/v4.1.9/codemap_4.1.9_linux_amd64.tar.gz"
      sha256 "8a1e1c09f52a5c2aa35371cc8aec9b7c9aac539867062bba43669641d574bba3"
      define_method(:install) do
        bin.install "codemap"
        (pkgshare/"sg-rules").install Dir["sg-rules/*.yml"] if Dir.exist?("sg-rules")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/codemap/releases/download/v4.1.9/codemap_4.1.9_linux_arm64.tar.gz"
      sha256 "60d9552955b4df0b1e060ba7b7017e897a603e03d763097aae68dfaba9682a43"
      define_method(:install) do
        bin.install "codemap"
        (pkgshare/"sg-rules").install Dir["sg-rules/*.yml"] if Dir.exist?("sg-rules")
      end
    end
  end

  def caveats
    <<~EOS
      The --deps mode uses ast-grep for code analysis.
    EOS
  end

  test do
    system "#{bin}/codemap", "--help"
  end
end
