# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmap < Formula
  desc "Instant documentation structure for LLMs and humans"
  homepage "https://github.com/JordanCoin/docmap"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.4.0/docmap_0.4.0_darwin_amd64.tar.gz"
      sha256 "0ea4d1e0fb5d2d263f543a6db75ed4de9cef10bbd21925710cfbf4a37c172072"

      define_method(:install) do
        bin.install "docmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.4.0/docmap_0.4.0_darwin_arm64.tar.gz"
      sha256 "d1f7918790ed4e22484f3a81cc6aaeb37f7e8e595b5d5df024bdd9d30aede627"

      define_method(:install) do
        bin.install "docmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.4.0/docmap_0.4.0_linux_amd64.tar.gz"
      sha256 "512035d515c17507ffe5b6c103d0f0a71a4a6fabe2f947b4cedc37a3ab5bbc48"
      define_method(:install) do
        bin.install "docmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.4.0/docmap_0.4.0_linux_arm64.tar.gz"
      sha256 "066866877e8b6ae6f41c5ac4f639c766c96c084c6165e93ed18492e155d3f7f9"
      define_method(:install) do
        bin.install "docmap"
      end
    end
  end

  test do
    system "#{bin}/docmap", "--help"
  end
end
