# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmap < Formula
  desc "Instant documentation structure for LLMs and humans"
  homepage "https://github.com/JordanCoin/docmap"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.0.2/docmap_0.0.2_darwin_amd64.tar.gz"
      sha256 "62cb8d95405ee87a2c4548b22703b593576721dfe5dca989d369411ac86a45f0"

      def install
        bin.install "docmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.0.2/docmap_0.0.2_darwin_arm64.tar.gz"
      sha256 "c8efdd166d34e64972d2c68250eb3a2d45865be8f44ba8a5bd2310c9cdb203f4"

      def install
        bin.install "docmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.0.2/docmap_0.0.2_linux_amd64.tar.gz"
      sha256 "08b3017c075e0804c6373ccc57c8a3fab8702647decf74cf048eb4e51b25f37f"
      def install
        bin.install "docmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/docmap/releases/download/v0.0.2/docmap_0.0.2_linux_arm64.tar.gz"
      sha256 "ebdfb1dd45789b960a96086db95673bc468a55bc8b18124b8d30656ebfca1925"
      def install
        bin.install "docmap"
      end
    end
  end

  test do
    system "#{bin}/docmap", "--help"
  end
end
