# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomap < Formula
  desc "Instant repository context for LLMs"
  homepage "https://github.com/JordanCoin/repomap"
  version "0.1.1"
  license "MIT"

  depends_on "codemap"
  depends_on "docmap"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordanCoin/repomap/releases/download/v0.1.1/repomap_0.1.1_darwin_amd64.tar.gz"
      sha256 "c7f4b214c75753402871dce3b76f7396c9361ef2d36c626bd4a767ca7b1ba415"

      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordanCoin/repomap/releases/download/v0.1.1/repomap_0.1.1_darwin_arm64.tar.gz"
      sha256 "be979451235d3f4db4cdb302845fe18d77cd1bf46c5913432d0fdbbe1f06f5d0"

      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/repomap/releases/download/v0.1.1/repomap_0.1.1_linux_amd64.tar.gz"
      sha256 "308c4b062babb8f2758b2f18db02d64e364246c72a72464d7357b1a8a2520131"
      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordanCoin/repomap/releases/download/v0.1.1/repomap_0.1.1_linux_arm64.tar.gz"
      sha256 "1d3ab55f03d41705df6153047f1ca7f46c2719fd48cd8a21df1230de795ac934"
      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  test do
    system "#{bin}/repomap", "--help"
  end
end
